### ISSUE TITLE
Documentation issue: param 'action' of type PARAM_ALPHA

### ISSUE THREAD

**Issue by PhMemmel** [learnweb/moodle-tool_lifecycle#139]
I stumbled over a more or less documentation issue trying to write my own step plugin including user interaction:

The function `abstract public function get_action_tools` in https://github.com/learnweb/moodle-tool_lifecycle/blob/884dc5d38adce16f221fc17761a9144fc10b253f/step/interactionlib.php#L67 needs to return an action string identifying the specific action the user has been chosen.

Unfortunately you cannot use **any** string here, because in `view.php` the param `action` is being defined as `PARAM_ALPHA`: https://github.com/learnweb/moodle-tool_lifecycle/blob/884dc5d38adce16f221fc17761a9144fc10b253f/view.php#L39

If you decide to use a string like "specific_user_action", it gets converted to `specificuseraction` when being submitted to `handle_interaction` which caused me some real headache today until I found the problem :-)

So maybe the param can be converted to another type than `PARAM_ALPHA` or at least this should be documented properly in the phpdoc for example of the abstract `get_action_tools` function in `interactionlib.php`.

If this is documented properly and I just didn't found it, sorry for the issue. Thanks in advance.

**Comment by NinaHerrmann** [comment]
Hey @PhMemmel,
thank you for your feedback, I have adjusted the wiki! If that's ok with you, I would close the issue :)
Cheers!

**Comment by PhMemmel** [comment]
Perfect, thank you!
