### ISSUE TITLE
Workflow definitions, activated workflows and deactivation

### ISSUE THREAD

**Issue by PetriAsi** [learnweb/moodle-tool_lifecycle#141]
Hi all,
this more like general question and I did not find answer from wiki.
I'm just curious why deactivated workflows does not return to definitions list, but deactivated list instead? 

It seem only way to "reactivate" deactivate workflow is make copy of it and activate that new copy instead.

**Comment by NinaHerrmann** [comment]
Hey @PetriAsi,
that is true. The main reason for this is to minimize the possibilities for errors. Activating and deactivating workflow might lead to complicated behaviours for courses that still run in the deactivated workflow or have been running in it. However, for usability I agree a warning or explanation would be nice. Does that clarify your question? 
Cheers, Nina

**Comment by PetriAsi** [comment]
Yes, thank you. 
 I can plan my work and our courses maintenance  according this.
