### ISSUE TITLE
Add lifecycletrigger_customfieldsemester to Wiki

### ISSUE THREAD

**Issue by abias** [learnweb/moodle-tool_lifecycle#153]
I would like to propose to add lifecycletrigger_customfieldsemester to the wiki page https://github.com/learnweb/moodle-tool_lifecycle/wiki/List-of-Additional-Subplugins#trigger. Unfortunately, there is no possibility to create pull requests for wiki pages, so I am creating this issue here.

This should be added to the page:

```
Customfield semester trigger

Link: https://github.com/hsh-elc/moodle-lifecycletrigger_customfieldsemester

Description: This trigger plugin triggers based on values of a custom course field of type "semester". 

Maintainer: Hochschule Hannover, Servicezentrum Lehre E-Learning (elc)
```

**Comment by ksteitz** [comment]
Thanks Alex!
Just added to the Wiki.
Further comments are welcome.
Cheers!

**Comment by ksteitz** [comment]
Thanks Alex!
Just added to the Wiki.
Further comments are welcome.
Cheers!
