### ISSUE TITLE
Provide a way to find view.php as a teacher.

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-tool_lifecycle#17]
The `view.php` is intended as a teacher frontend for managing their courses. However, there is no navigation item that teachers can use to find it.

Add an entry into the settings navigation to enter the `view.php`. The `view.php` is a global management frontend, so it should not be a "course setting", but maybe a new setting menu altogether (on the same level as "course settings".

**Comment by Dagefoerde** [comment]
Might require a local plugin just for adding this link to the navigation, but this needs further investigation first.

**Comment by tobiasreischmann** [comment]
We still can think about moving the menu entry elsewhere. Currently it is placed in the course menu

**Comment by Dagefoerde** [comment]
I think that, for now, it is easy to find there. Right now, the "standard" workflows operate on a single course, so I would close this for now. Once we have a couple of workflows that work without an existing course, we may reconsider (and open a more specific issue then).
