### ISSUE TITLE
Bug: workflowoverview page causes memory overflow on big instances

### ISSUE THREAD

**Issue by PhMemmel** [learnweb/moodle-tool_lifecycle#170]
On big instances it is not possible anymore to configure any workflows, because trying to create a new one or editing an existing one will exceed the memory the request can take. This is likely to be caused by the fact that the check function of *every* configured trigger will be called *for every single course* just to show the number of courses which will be triggered in the workflowoverview page (see `get_count_of_courses_to_trigger_for_workflow` function).

I admit, it's a nice feature, but on instances with a lot of courses (for example ~400 000), this will exceed the memory stack and make the whole plugin unusable, because you cannot configure any workflow anymore. I believe this can also be an issue if triggers with pretty complex `check_course` functions are being used (including expensive SQL statements on big tables), so probably this not only can cause memory exhaustion, but can also lead to timeouts if the request takes too long to perform.

**Comment by NinaHerrmann** [comment]
Hey @PhMemmel , 
I see your point do you have any suggestions for a fix?

**Comment by PhMemmel** [comment]
Hi @NinaHerrmann,

I already provided a patch, but did not link it properly, sorry for that. It's now properly linked :-)

**Comment by NinaHerrmann** [comment]
Sorry! I requested one of our student assistants to review it, but looks good!
