### ISSUE TITLE
Unknown column 'processes' in 'order clause'

### ISSUE THREAD

**Issue by melanietreitinger** [learnweb/moodle-tool_lifecycle#175]
Got to Site administration -> Plugins -> Admin tools -> Life Cycle -> Workflow settings:

You need active manual workflows.

Click on the "Active processes" link: 

![grafik](https://user-images.githubusercontent.com/66598405/228888419-9598fd33-a788-4563-8fba-ebef31cf64ee.png)

This results in an error:

![grafik](https://user-images.githubusercontent.com/66598405/228888755-fb39a5f2-e449-466a-af1b-f4573dfc5d69.png)

As a workaround you can add `?treset=true` to the url.

**Comment by justusdieckmann** [comment]
Sorry for the delay and thank you very much for reporting the issue!
