### ISSUE TITLE
Icon of the manual trigger is not displayed

### ISSUE THREAD

**Issue by KerstinSc** [learnweb/moodle-tool_lifecycle#176]
Hello!

We have tried to configure a manual workflow (with manual trigger). The workflow works fine, but the icon (as specified in the example core/tick) is not displayed. It seems that the icon is not found.

What are we doing wrong? 

I have to say, we are testing the plugin with Moodle 4.1 with the boost theme. Was there maybe a change that is not yet implemented in the plugin?

Thank you!

**Comment by KerstinSc** [comment]
I've provided #193 for this minor issue

**Comment by NinaHerrmann** [comment]
Thank you very much for providing the solution!
