### ISSUE TITLE
Uploading a workflow with categories that do not exist throws errors. 

### ISSUE THREAD

**Issue by NinaHerrmann** [learnweb/moodle-tool_lifecycle#194]
When downloading a workflow (wf) that uses a category trigger the upload can not handle unknown categories. 
The .XML file uses the id of the categories to identify the categories to be used. When this ID is not allocated in the system e.g. 
 https://github.com/learnweb/moodle-tool_lifecycle/blob/38d6dc78f586d31b2ab3a9fe89a4ad707a7ef9b3/trigger/categories/lib.php#L79 
 throws `Call to a member function get_all_children_ids() on bool `.

To the best of my knowledge, the most reasonable behavior would be to either 
a) delete the category trigger completely during the upload process. 
b) replace the category with some random category 
and provide a warning to the user.

I am not completely happy with both options but I guess implementing a category selection option during the upload process is overkill.

**Comment by lucaboesch** [comment]
The proposed fix contains

```
            array_push($allcategories, $category);
            if (!isset($categoryobjects[$category]) || !$categoryobjects[$category]) {
                continue;
            }
            $children = $categoryobjects[$category]->get_all_children_ids();
            $allcategories = array_merge($allcategories, $children);
```

Sorry for the noise.
All good.

I think this issue can also appear if you delete a category (that has already been emptied) whilst the process of backup and delete in a category trigger is still ongoing. Then, at a certain point, this hits.
