### ISSUE TITLE
Question: possible to create subplugins for user lifecycle management?

### ISSUE THREAD

**Issue by bozicm** [learnweb/moodle-tool_lifecycle#202]
Hello, I was looking for alternatives for https://moodle.org/plugins/tool_usersuspension. I was wondering if similar features could be implemented with subplugins in your plugin. After a quick glance over the documentation I'm not so sure, because it seems to be quite tightly coupled with course functions. Or am I mistaken?

Thanks,
Martin

**Comment by NinaHerrmann** [comment]
Hey @bozicm,
maybe you could elaborate on the functionality that you need?
I do not know tool_usersuspension.
Best regards,
Nina

**Comment by bozicm** [comment]
We'd like to check on users that haven't logged for a certain period.
After that period we would send them a notification that their account
will be suspended unless they login into Moodle. Then, after a certain
period of suspension, the account would get deleted.

**Comment by ksteitz** [comment]
yes, you may use tool_cleanupusers. For the future we are also planning to get in in the moodle.org plugins directory. Just ask if you have questions...
