### ISSUE TITLE
string 'config_delay_duration_desc' is hard to understand

### ISSUE THREAD

**Issue by lucaboesch** [learnweb/moodle-tool_lifecycle#28]
I struggle to understand what $string['config_delay_duration_desc'] means.

Defines the time frame, which a course is excluded from the life cycle processes, when rolled back via user interaction.

Is that maybe '…, by which'?
Or '…, after which'? '…, during which'?

I have to say my english is not perfect. Nevertheless, that description is not super easy to come by. It could be rephrased in a simpler english, I think.

Thanks!

**Comment by Dagefoerde** [comment]
Yes, you are right. Here's a suggestion:
"After roll back via user interaction, this setting specifies the time span for which a course will be exempted from all processes."

What do you think?

**Comment by lucaboesch** [comment]
That sounds much more comprehensible. Go ahead!
