### ISSUE TITLE
Make backups downloadable

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-tool_lifecycle#4]
Add a button to not only restore the course backup files directly, but also to simple download the zip files.

**Comment by Dagefoerde** [comment]
Which backups?

**Comment by tobiasreischmann** [comment]
The backups created by the createbackup step. Those are listed on the site Course Backups in the Site Administration. Currently, there is only a restore button. Although, the backups are stored in a separate folder in the Moodledata folder, it might be interesting for admins, to have the possibility to directly download them.
