### ISSUE TITLE
Add step for making courses invisible

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-tool_lifecycle#48]
The step should also save the previous visibility to restore it in case of rollback.

**Comment by tobiasreischmann** [comment]
This step should not be part of the core, but placed outside. Maybe we could make a wiki page, which gathers all available steps and trigger.

**Comment by tobiasreischmann** [comment]
I created this page: https://github.com/learnweb/moodle-tool_lifecycle/wiki/List-of-Subplugins

**Comment by justusdieckmann** [comment]
I created the step: https://github.com/learnweb/moodle-lifecyclestep_makeinvisible

**Comment by justusdieckmann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IS #48](https://trello.com/c/RoAaZyL4/24-is-48)

**Comment by tobiasreischmann** [comment]
Thanks for the step plugin :)
